-- MySQL Script generated by MySQL Workbench
-- Thu Nov 18 17:59:12 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema safers
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema safers
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `safers` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `safers` ;

-- -----------------------------------------------------
-- Table `safers`.`map`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `safers`.`map` (
  `id` VARCHAR(13) NOT NULL,
  `name` VARCHAR(30) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `safers`.`animals`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `safers`.`animals` (
  `id` VARCHAR(13) NOT NULL,
  `name` VARCHAR(30) NULL DEFAULT NULL,
  `map_id` VARCHAR(13) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FKerblrhlm4ouy82ki58iheekwd` (`map_id` ASC) VISIBLE,
  CONSTRAINT `FKerblrhlm4ouy82ki58iheekwd`
    FOREIGN KEY (`map_id`)
    REFERENCES `safers`.`map` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `safers`.`common_code`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `safers`.`common_code` (
  `common_code` VARCHAR(3) NOT NULL,
  `name` VARCHAR(15) NULL DEFAULT NULL,
  PRIMARY KEY (`common_code`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `safers`.`code`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `safers`.`code` (
  `code` VARCHAR(3) NOT NULL,
  `name` VARCHAR(15) NULL DEFAULT NULL,
  `use_yn` BIT(1) NULL DEFAULT NULL,
  `common_code` VARCHAR(3) NULL DEFAULT NULL,
  PRIMARY KEY (`code`),
  INDEX `FK86varlw7buh4xqhs7qwfvdffo` (`common_code` ASC) VISIBLE,
  CONSTRAINT `FK86varlw7buh4xqhs7qwfvdffo`
    FOREIGN KEY (`common_code`)
    REFERENCES `safers`.`common_code` (`common_code`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `safers`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `safers`.`user` (
  `id` VARCHAR(13) NOT NULL,
  `kakao_id` BIGINT NULL DEFAULT NULL,
  `nick_name` VARCHAR(15) NULL DEFAULT NULL,
  `profile_url` VARCHAR(255) NULL DEFAULT NULL,
  `code` VARCHAR(3) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FKdpwkuedqkkkv9mruxtg1l813j` (`code` ASC) VISIBLE,
  CONSTRAINT `FKdpwkuedqkkkv9mruxtg1l813j`
    FOREIGN KEY (`code`)
    REFERENCES `safers`.`code` (`code`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `safers`.`animals_log`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `safers`.`animals_log` (
  `reg_dt` TIMESTAMP NULL DEFAULT NULL,
  `animals_id` VARCHAR(13) NOT NULL,
  `user_id` VARCHAR(13) NOT NULL,
  PRIMARY KEY (`user_id`, `animals_id`),
  INDEX `FK3vmxre31p7v2ky8mu92kgyfs3` (`animals_id` ASC) VISIBLE,
  CONSTRAINT `FK3vmxre31p7v2ky8mu92kgyfs3`
    FOREIGN KEY (`animals_id`)
    REFERENCES `safers`.`animals` (`id`),
  CONSTRAINT `FK9glm9px1svux31d5uwiuibwxm`
    FOREIGN KEY (`user_id`)
    REFERENCES `safers`.`user` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `safers`.`board`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `safers`.`board` (
  `id` VARCHAR(13) NOT NULL,
  `content` TEXT NULL DEFAULT NULL,
  `is_delete` BIT(1) NULL DEFAULT NULL,
  `reg_dt` TIMESTAMP NULL DEFAULT NULL,
  `title` VARCHAR(50) NULL DEFAULT NULL,
  `user_id` VARCHAR(13) NULL DEFAULT NULL,
  `code` VARCHAR(3) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FKfyf1fchnby6hndhlfaidier1r` (`user_id` ASC) VISIBLE,
  INDEX `FK33qyqeppvf1jde3wovojv9d7e` (`code` ASC) VISIBLE,
  CONSTRAINT `FK33qyqeppvf1jde3wovojv9d7e`
    FOREIGN KEY (`code`)
    REFERENCES `safers`.`code` (`code`),
  CONSTRAINT `FKfyf1fchnby6hndhlfaidier1r`
    FOREIGN KEY (`user_id`)
    REFERENCES `safers`.`user` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `safers`.`board_comment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `safers`.`board_comment` (
  `id` VARCHAR(13) NOT NULL,
  `comment` TEXT NULL DEFAULT NULL,
  `is_delete` BIT(1) NULL DEFAULT NULL,
  `nick_name` VARCHAR(15) NULL DEFAULT NULL,
  `reg_dt` TIMESTAMP NULL DEFAULT NULL,
  `user_id` VARCHAR(13) NULL DEFAULT NULL,
  `board_id` VARCHAR(13) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FKke01v1gkigv4065kfl3aavje6` (`board_id` ASC) VISIBLE,
  CONSTRAINT `FKke01v1gkigv4065kfl3aavje6`
    FOREIGN KEY (`board_id`)
    REFERENCES `safers`.`board` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `safers`.`board_image`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `safers`.`board_image` (
  `id` VARCHAR(13) NOT NULL,
  `file_name` TEXT NULL DEFAULT NULL,
  `file_path` TEXT NULL DEFAULT NULL,
  `board_id` VARCHAR(13) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FKp567mlnww479xgirmd98kcqnp` (`board_id` ASC) VISIBLE,
  CONSTRAINT `FKp567mlnww479xgirmd98kcqnp`
    FOREIGN KEY (`board_id`)
    REFERENCES `safers`.`board` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `safers`.`map_log`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `safers`.`map_log` (
  `reg_dt` TIMESTAMP NULL DEFAULT NULL,
  `user_id` VARCHAR(13) NOT NULL,
  `map_id` VARCHAR(13) NOT NULL,
  PRIMARY KEY (`user_id`, `map_id`),
  INDEX `FKr59ehm4mofk3ql3q2b07u2qfi` (`map_id` ASC) VISIBLE,
  CONSTRAINT `FKfhjus5yokluwbj9w6c371605h`
    FOREIGN KEY (`user_id`)
    REFERENCES `safers`.`user` (`id`),
  CONSTRAINT `FKr59ehm4mofk3ql3q2b07u2qfi`
    FOREIGN KEY (`map_id`)
    REFERENCES `safers`.`map` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `safers`.`mission`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `safers`.`mission` (
  `id` VARCHAR(13) NOT NULL,
  `next_mission` TEXT NULL DEFAULT NULL,
  `result_id` TEXT NULL DEFAULT NULL,
  `title` TEXT NULL DEFAULT NULL,
  `animal_name` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `safers`.`mission_log`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `safers`.`mission_log` (
  `reg_dt` TIMESTAMP NULL DEFAULT NULL,
  `mission_id` VARCHAR(13) NOT NULL,
  `code` VARCHAR(3) NULL DEFAULT NULL,
  `user_id` VARCHAR(13) NOT NULL,
  PRIMARY KEY (`user_id`, `mission_id`),
  INDEX `FKm1mppucbggl93qrclongtdh93` (`mission_id` ASC) VISIBLE,
  INDEX `FKmds6478yfrlsef821k11q25es` (`code` ASC) VISIBLE,
  CONSTRAINT `FKfc6sr274y588qui9x2nj911ra`
    FOREIGN KEY (`user_id`)
    REFERENCES `safers`.`user` (`id`),
  CONSTRAINT `FKm1mppucbggl93qrclongtdh93`
    FOREIGN KEY (`mission_id`)
    REFERENCES `safers`.`mission` (`id`),
  CONSTRAINT `FKmds6478yfrlsef821k11q25es`
    FOREIGN KEY (`code`)
    REFERENCES `safers`.`code` (`code`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `safers`.`survey`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `safers`.`survey` (
  `mbti` VARCHAR(5) NOT NULL,
  `area` VARCHAR(30) NULL DEFAULT NULL,
  `buddy` TEXT NULL DEFAULT NULL,
  `enemy` TEXT NULL DEFAULT NULL,
  `explanation` TEXT NULL DEFAULT NULL,
  `extinction` TEXT NULL DEFAULT NULL,
  `image_url` VARCHAR(200) NULL DEFAULT NULL,
  `introduce` TEXT NULL DEFAULT NULL,
  `personality` TEXT NULL DEFAULT NULL,
  `name` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`mbti`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `safers`.`token`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `safers`.`token` (
  `access_token` VARCHAR(255) NULL DEFAULT NULL,
  `refresh_token` VARCHAR(255) NULL DEFAULT NULL,
  `user_id` VARCHAR(13) NOT NULL,
  `id` VARCHAR(13) NULL DEFAULT NULL,
  PRIMARY KEY (`user_id`),
  CONSTRAINT `FKe32ek7ixanakfqsdaokm4q9y2`
    FOREIGN KEY (`user_id`)
    REFERENCES `safers`.`user` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
